version: "2"

services:
  vault_server:
    networks:
      - develop
    image: "cypherhat/vault-ethereum:latest"
    ports:
      - "9200:9200"
    volumes:
      - "./config:/home/vault/config:rw"
    entrypoint: /home/vault/config/entrypoint.sh


  vault_postgresql:
    container_name: "Vault-PostgreSQL"
    image: postgres:14.1-alpine
    networks:
     - develop
    ports:
     - "2345:5432"
    environment:
      - POSTGRES_USER=$PG_USER
      - POSTGRES_PASSWORD=$banhcanh
      - POSTGRES_DB=$PG_DB
    volumes:
      - ./var/pgdata:/var/lib/postgresql/data
      - ../sqls/init.sql:/docker-entrypoint-initdb.d/init.sql




        #  ganache:
#    networks:
#      - develop
#    image: trufflesuite/ganache-cli:latest
#    ports:
#      - "8545:8545"
#    volumes:
#      - ./ganache_data:/ganache_data
#    entrypoint:
#      - node
#      - /app/ganache-core.docker.cli.js
#      - --deterministic
#      - --db=/ganache_data
#      - --mnemonic
#      - "volcano story trust file before member board recycle always draw fiction when"
#      - --networkId
#      - "8545"
#      - --hostname
#      - "0.0.0.0"

networks:
  develop:
    driver: bridge
